apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: joshix-poi-backend-app-dev
  annotations:
    argocd/app-name: joshix-poi-backend-app-dev
    backstage.io/kubernetes-id: joshix-poi-backend-app-dev
    backstage.io/kubernetes-namespace: joshix
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=joshix-poi-backend-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rosa916-rvhvd/joshix-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/dev-pipelines/ns/joshix/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/k8s/ns/joshix/deployments/joshix-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa916.9nln.p1.openshiftapps.com/#https://github.com/rosa916-rvhvd/joshix-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/joshix"
  system: workshop-system-joshix
  providesApis:
    - backend-api-joshix
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-joshix
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/joshix"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-joshix
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://joshix-poi-backend-app-joshix.apps.rosa916.9nln.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rosa916-rvhvd/joshix-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/joshix"
  system: workshop-system-joshix
  definition:
    $text: https://github.com/rosa916-rvhvd/joshix-backend/tree/main/src/main/resources/META-INF/openapi.yaml
